# Sightstone constants

SIGHTSTONE = "Sightstone"

# Map IDS
SUMMONERS_RIFT_ID   = 11
HOWLING_ABYSS_ID    = 12
STR_TO_MAP          = {
    "Summoner's rift": SUMMONERS_RIFT_ID,
    "Howling Abyss": HOWLING_ABYSS_ID
}

# Gamemodes
PRACTICE_TOOL_MODE  = "PRACTICETOOL"
ARAM_MODE           = "ARAM"
CLASSIC_MODE        = "CLASSIC"

# Lobby creation
CLASH_ID            = "700"
QUICK_PLAY_ID       = "490"
DRAFT_PICK_ID       = "400"
FLEX_PLAY_ID        = "440"
SOLO_DUO_ID         = "420"
ARAM_PLAY_ID        = "450"
ARAM_5V5_BOTS       = "860"
ARENA_ID            = "1700"
TUTORIAL_1_ID       = "2000"
TUTORIAL_2_ID       = "2010"
TUTORIAL_3_ID       = "2020"
INTRO_ID            = "830"
BEGGINER_ID         = "840"
INTERMEDIATE_ID     = "850"
ARURF_ID            = "900"
ARURF_1V1_ID        = "901"
NEXUS_BLITZ_ID      = "1300"
TFT_NORMAL_ID       = "2200"
TFT_RANKED_ID       = "1100"
TFT_TUTORIAL_ID     = "1110"
TFT_DOUBLE_UP_ID    = "1160"
TFT_HYPERROLL_ID    = "1130"

# Roles
TOP_ID      = "0"
JGL_ID      = "1"
MID_ID      = "2"
ADC_ID      = "3"
SUP_ID      = "4"
FILL_ID     = "5"
NONE_ID     = "6"

# Reveal lobby available websites
OP_GG           = "OP.GG"
U_GG            = "U.GG"
PORO_GG         = "PORO.GG"
POROFESSOR_GG   = "Porofessor.gg"

# Queue
QUEUE_SEARCHING = "Searching"
QUEUE_FOUND     = "Found"
QUEUE_INVALID   = "Invalid"

# Availability
ONLINE_AVAILABILITY     = "online"
AWAY_AVAILABILITY       = "away"
MOBILE_AVAILABILITY     = "mobile"
OFFLINE_AVAILABILITY    = "offline"

# Ranks
IRON_RANK           = "IRON"
BRONZE_RANK         = "BRONZE"
SILVER_RANK         = "SILVER"
GOLD_RANK           = "GOLD"
PLATINUM_RANK       = "PLATINUM"
EMERALD_RANK        = "EMERALD"
DIAMOND_RANK        = "DIAMOND"
MASTER_RANK         = "MASTER"
GRANDMASTER_RANK    = "GRANDMASTER"
CHALLENGER_RANK     = "CHALLENGER"

DIVISION_I      = "I"
DIVISION_II     = "II"
DIVISION_III    = "III"
DIVISION_IV     = "IV"

SOLODUO_QUEUE_CODE          = "RANKED_SOLO_5x5"
FLEX_QUEUE_CODE             = "RANKED_FLEX_SR"
TWISTED_TREELINE_QUEUE_CODE = "RANKED_FLEX_TT"
TFT_QUEUE_CODE              = "RANKED_TFT"
TFT_TURBO_QUEUE_CODE        = "RANKED_TFT_TURBO"
TFT_DOUBLE_UP_QUEUE_CODE    = "RANKED_TFT_DOUBLE_UP"
ARENA_QUEUE_CODE            = "CHERRY"

# Loot
CHAMPION_SHARD_TYPE = "CHAMPION_RENTAL"
CHAMPION_PERMANENT_TYPE = "CHAMPION"
CHAMPION_TOKEN_TYPE = "CHAMPION_TOKEN"
SKIN_SHARD_TYPE = "SKIN_RENTAL"
SKIN_PERMANENT_TYPE = "CHAMPION_SKIN"
ETERNAL_TYPE_1 = "STATSTONE_SHARD"
ETERNAL_TYPE_2 = "STATSTONE"
WARD_SHARD_TYPE = "WARDSKIN_RENTAL"
WARD_PERMANENT_TYPE = "WARD_SKIN"
EMOTE_TYPE = "EMOTE"
ICON_TYPE = "SUMMONER_ICON"
COMPANION_TYPE = "COMPANION"
